language: cpp
dist: trusty

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-test-dev
      - g++-7
      - doxygen
      - graphviz
# env:
  # - CXX=g++-7
  # - cc=gcc-7

before_script:
  - mkdir build
  - cd build
  - export CXX=g++-7
  - cmake .. -DCMAKE_BUILD_TYPE=Release
script:
  - make
  - make test
  - make docs

deploy:
  provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch: master

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GH_REPO_TOKEN
  local-dir: ../docs
