language: cpp
dist: trusty

addons:
  apt:
    packages:
      - libboost-test-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test

deploy:
  provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch: master
