language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-test-dev
      - g++-7
env:
  - CXX=g++-7
  - cc=gcc-7

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test

deploy:
  provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch: master
